name: React Image Gallery
markdown: redcarpet
highlighter: null # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json",  "README.md", "_scripts", "_scss", "gemfile", "Gemfile.lock"]
url: "https://eli-nathan.github.io/React-Image-Gallery/"
destination: docs
baseurl: "/React-Image-Gallery"
